image: php:7.2

stages:
  - test

test:
  stage: test
  before_script:
    - curl --silent --show-error https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
  script:
    - composer install
    - vendor/bin/phpunit
